Repository virtual-tackle-box/front-end-vtb, pull requests merged in 2023-10, with the labels that each got.

#2 Setup/cypress
  App.js
  cypress.config.js
  cypress/e2e/login.spec.cy.js
  cypress/fixtures/example.json
  cypress/support/commands.js
  cypress/support/e2e.js
  package-lock.json
  package.json
Labels: testing

#3 Setup/circleci
  .circleci/config.yml
  App.js
  cypress/e2e/login.cy.js
  cypress/e2e/login.spec.cy.js
  cypress/e2e/spec.cy.js
  package-lock.json
  package.json
Labels: enhancement

#15 Feature/catch form
  App.js
  components/AddCatch/AddCatch.js
  components/AddCatch/AddCatchStylesheet.js
  components/AddCatch/AddFish/AddFish.js
  components/AddCatch/AddFish/AddFishStylesheet.js
  components/AddCatch/AddSpot/AddSpot.js
  components/AddCatch/AddSpot/AddSpotStylesheet.js
  components/AddCatch/LureForm/LureForm.js
  components/AddCatch/LureForm/LureFormStylesheet.js
  components/AddCatch/UploadPhoto/UploadPhoto.js
  components/AddCatch/UploadPhoto/UploadPhotoStylesheet.js
  components/Dashboard/Dashboard.js
  components/Dashboard/DashboardStylesheet.js
  components/Login/Login.js
  components/Login/LoginStyles.js
  package-lock.json
  package.json
Labels: enhancement

#21 Feature/catch form
  components/AddCatch/AddCatch.js
  components/AddCatch/AddFish/AddFish.js
  components/AddCatch/AddSpot/AddSpot.js
  components/AddCatch/LureForm/LureForm.js
  cypress/e2e/catch.cy.js
  cypress/e2e/dashboard.cy.js
Labels: enhancement

#26 Feature/books
  App.js
  components/AddCatch/AddCatch.js
  components/Books/BooksDashStylesheet.js
  components/Books/BooksDashboard.js
  components/Books/CatchLog/CatchLog.js
  components/Books/CatchLog/CatchLogStylesheet.js
  components/Books/Tackle/Tackle.js
  components/Books/Tackle/TackleStylesheet.js
  components/Dashboard/Dashboard.js
  components/TestLogBook/TestLogBook.js
  fetchCalls.js
Labels: enhancement

#28 Swap mock server for heroku url
  components/AddCatch/AddSpot/AddSpot.js
  fetchCalls.js
Labels: enhancement

#32 Feature/delete catches
  components/AddCatch/AddCatch.js
  components/Books/CatchLog/CatchLog.js
  fetchCalls.js
Labels: enhancement

#48 Feature/cloudinary
  components/AddCatch/AddCatch.js
  components/AddCatch/UploadPhoto/UploadPhoto.js
  components/Books/CatchLog/CatchLog.js
  components/Books/CatchLog/CatchLogStylesheet.js
  components/Map/UserMap.js
  fetchCalls.js
Labels: enhancement

#52 Create README.md
  README.md
Labels: documentation

#53 Update README.md with preview video
  README.md
Labels: documentation
